version: '2'

services:
    webapp:
        image: incident-management-webapp
        ports:
            - 3000:3000
        environment:
            - SERVER_URL=http://nodejs:8080/
        depends_on:
            - nodejs

    couchdb:
        image: incident-management-db
        ports:
            - 5984:5984

    nodejs:
        image: incident-management-server
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=dev
            - APPLICATION_PORT=8080
            - COUCHDB_URL=http://couchdb:5984/
        restart: always