export default {
    USER_LOGIN: 'USER_LOGIN',
    ASSIGN_INCIDENT: 'ASSIGN_INCIDENT',
    ACKNOWLEDGE_INCIDENT: 'ACKNOWLEDGE_INCIDENT',
    RESOLVE_INCIDENT: 'RESOLVE_INCIDENT',
    DELETE_INCIDENT: 'DELETE_INCIDENT',
    SELECT_INCIDENT: 'SELECT_INCIDENT',
    LIST_INCIDENTS: 'LIST_INCIDENTS'
}